spring:
  application:
    name: v1
  profiles:
    group:
      local: [local, default-datasource, swagger, redis, security, spotify]
      dev: [dev, dev-datasource, swagger, redis, security, spotify]
    active: ${PROFILE_ACTIVE:local}


